# Generated by Django 3.0 on 2019-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Super recept! Usudi se probati...', max_length=25),
        ),
    ]
