# Generated by Django 3.0 on 2019-12-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0003_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media\\post_pics\\default.jpg', upload_to=''),
        ),
    ]
