# Generated by Django 3.0 on 2019-12-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0004_auto_20191210_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Super recept! Usudi se probati...', max_length=200),
        ),
    ]
