# Generated by Django 3.0 on 2019-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0006_auto_20191211_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_pics\\default.jpg', upload_to='post_pics'),
        ),
    ]
