# Generated by Django 3.0 on 2019-12-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0008_auto_20191211_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='naslov',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='sadrzaj',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='sazetak',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='slika',
            field=models.ImageField(default='default.png', upload_to='post_pics'),
        ),
    ]
