# Generated by Django 3.0 on 2019-12-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
