# Generated by Django 3.0 on 2020-01-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0014_auto_20200119_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
