# Generated by Django 3.0 on 2020-01-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0015_remove_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
